# Generated by Django 2.2.5 on 2019-09-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='summory',
            new_name='body',
        ),
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.TextField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(default=21),
            preserve_default=False,
        ),
    ]
