# Generated by Django 2.2.5 on 2019-09-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190913_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
