# Generated by Django 2.2.5 on 2019-09-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190913_0256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
